# Team Mobile Madness

---

You are on the data science department of a mobile device company. In an effort to extend account lifetime of existing customers, we need to develop targeted A/B experiments. In order to do that efficiently, we need to have a better degree of certainty about which customers are likely to to "churn" and why.

**Goals:**
- Research the concept of "churn" and A/B testing.
- Identify behaviors strongly correlated with churn in this dataset.
- Suggest what we should develop A/B tests for going forward.

**Presentation requirements:**
- Concisely explain churn and A/B testing to the audience.
- At least 50% of presentation must address a non-technical audience.
- Someone who hasn't presented in class yet must take lead on presentation.

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

%matplotlib inline

df = pd.read_csv("./datasets/churn-bigml-20.csv")

In [2]:
df.head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,LA,117,408,No,No,0,184.5,97,31.37,351.6,80,29.89,215.8,90,9.71,8.7,4,2.35,1,False
1,IN,65,415,No,No,0,129.1,137,21.95,228.5,83,19.42,208.8,111,9.40,12.7,6,3.43,4,True
2,NY,161,415,No,No,0,332.9,67,56.59,317.8,97,27.01,160.6,128,7.23,5.4,9,1.46,4,True
3,SC,111,415,No,No,0,110.4,103,18.77,137.3,102,11.67,189.6,105,8.53,7.7,6,2.08,2,False
4,HI,49,510,No,No,0,119.3,117,20.28,215.1,109,18.28,178.7,90,8.04,11.1,1,3.00,1,False